### ISSUE TITLE
Upgraded to HA 2023.7.3 integration stopped working

### ISSUE THREAD

**Issue by pupe666** [basilfx/homeassistant-biketrax#100]
First of all, thanks for a great integration.

Since I uppgraded to Home Assistant 2023.7.3 (I think) it stopped working. I tried to remove the integration and re-add it but still same problem.
<img width="530" alt="image" src="https://github.com/basilfx/homeassistant-biketrax/assets/97130254/0848f4d3-b3a3-4f49-8061-e8ffa55f288a">

debuggin is writing this in the log:
`Config entry 'BikeTrax <MyEmail>@gmail.com' for biketrax integration not ready yet: A BikeTrax error occurred while updating the subscription data: Unable to parse API response.; Retrying in background-`

My subscription to biketrax is valid to 2:nd of august

**Comment by basilfx** [comment]
Can you see if you are able to install the latest `master` version? I'm currently testing this locally, before I create a 1.1.0 release.

**Comment by pupe666** [comment]
I tried to do that, but im not 100% sure if I did it right. 
I updated the manifest.json but I'm not sure the formatting is correct. 
I then uninstalled the dependency. But i still get the same error after a restart.

My updated manifest.json (had to change fileformat to upload the file)
[manifest.txt](https://github.com/basilfx/homeassistant-biketrax/files/12175284/manifest.txt)

**Comment by pupe666** [comment]
I have now managed to remove the dependency error, as I thougt, it belonged to another integration/configuration. Sorry for the confusion.

I'm a total beginner in linux and also not a developer ;(, but the package doesnt seem to exist when I do a pip list, should it not be listed. Is there any way i can check that the development depencency is installed?

I understand that I might not be of any good help with my limited knowlede. But let me know if there is something else I can do.

and again this is a really nice integration, keep up the good work.

**Comment by basilfx** [comment]
Version 1.1.0 has been released. Please open a new issue if you encounter problems with it.
