### ISSUE TITLE
Unable to connect to API

### ISSUE THREAD

**Issue by tonyschuite** [basilfx/homeassistant-biketrax#107]
Just updated to lates HA and HAOS.
i get the following error:

A BikeTrax error occured while updating the trips: unable to connect to remote API

2023-08-27 10:59:32.024 DEBUG (MainThread) [aiobiketrax.api] GET request to 'https://traccar.powunity.com/api/reports/trips' returned HTTP status code 200.

https://traccar.powunity.com/api/reports/trips --> site cant be reached
https://traccar.powunity.com/api/reports/ --> HTTP 404 Not Found - NotFoundException (...)
https://traccar.powunity.com/api/  --> HTTP 404 Not Found - NotFoundException (...)
https://traccar.powunity.com/ --> allows me to login and see my bike

**Comment by wolicape** [comment]
Hi, 

Got the same here. HTTP code 200 but component gets success False, except that i can't even login into https://traccar.powunity.com/

**Comment by basilfx** [comment]
It seems that, with an 'Accept' header in the GET request, the result is an XLSX file, instead of JSON. By adding the header, it seems to work again.

**Comment by wolicape** [comment]
Hi, thanks for your investigations. Unfortunely, it doesn't seems to solve anything on my side. I've still got the same issue and debug messages, even after a reinstallation in HACS and a restart of my HA.

**Comment by basilfx** [comment]
Are you sure that you have included the fix properly? I was able to reproduce this issue, and I can confirm that it works with the fix.

A fix for this was included in `aiobiketrax=1.1.1`. Modify the `manifest.json` locally, and restart Home Assistant to check it out.

If it does not work, please post another debug log.

**Comment by wolicape** [comment]
Well seen, the version had remained in 1.1.0 for aiobiketrax. Modified as recommended, it works like a charm now !

Great work, thank you very much 💯

**Comment by tonyschuite** [comment]
same here. fixed now. Thanks for this!
