### ISSUE TITLE
Change the Alarm switch and rename it to something clearer

### ISSUE THREAD

**Issue by vlebourl** [basilfx/homeassistant-biketrax#11]
Hey, 

I wonder whether the `switch.biketrax_is_guarded` could be renamed to something clearer. It took me a minute the first time to realize it was actually the big button in the app to arm/disarm the alarm. Maybe something like `Arm alarm` instead of just `Alarm`? And for the entity `switch.biketrax_is_alarm_armed`?

And thinking of this, I was actually wondering whether it would be worth changing this entity from a switch to a lock or an actual alarm control panel, although I think the latter would be overkill, as there is no code nor home/night/away modes. 

What are your thoughts?

Cheers

**Comment by gllmlbrt** [comment]
Hi I was thinking the same. I manually renamed it to "Guard" and changed the icon to `mdi:shield-lock` and `mdi:shield-lock-opened` depending on the sate, as well as color. To strictly follow the in-app concepts.
It is not the alarm, rather a switch to set whether the guarded state is armed or not.
![image](https://user-images.githubusercontent.com/58825251/183603246-19e93f8a-9c4f-4037-a934-f079567fa343.png) 
![image](https://user-images.githubusercontent.com/58825251/183603774-d1edf3eb-8459-47c2-aae2-4b5df5efa07c.png)


could also be turned into a lock entity with the lock integration:
![image](https://user-images.githubusercontent.com/58825251/183604241-6dcfcfc8-af69-414f-ba04-c4d44eecf1f6.png)

**Comment by vlebourl** [comment]
You can have a look at #12  for a control panel implementation.

**Comment by gllmlbrt** [comment]
Yes was looking through it. I am a bit unsure whether Alarm integration with control panel is warranted here... seems a little oversized. It is just a lock feature actually.
But I still see a potential benefit to have an Armed Home and Armed Away possibility, having different automation/trigger in case of an alarm.

**Comment by vlebourl** [comment]
Having it as an alarm allows to add the `triggered` state with a flashy card if the alarm is triggered, I do like it ^_^

**Comment by basilfx** [comment]
My very first implementation used a lock first. That did not really 'fit'. I have thought about an alarm implementation, but did not consider it due to the overhead. I'll take a look as #12 to see if it suits. That said, maybe HASS might relax the concept of an alarm in the future.

**Comment by vlebourl** [comment]
What overhead are you talking about? It does add some code but the new entity is very simple. And arming/disarming and triggered alarm fits the app's behaviour quite well, even with auto-guard, don't you think?

**Comment by basilfx** [comment]
I agree. I was referring to the overhead of the entity type, not of the code :-)

**Comment by basilfx** [comment]
#12 (or, actually #46) got merged, so I think this can be closed.
