### ISSUE TITLE
Unexpected error fetching biketrax-XXX@gmail.com-subscription data: Parser must be a string or character stream, not NoneType

### ISSUE THREAD

**Issue by gyusza** [basilfx/homeassistant-biketrax#91]
Like the title says, after having set up the application and double checking all the login details, i get the following error in the logs in Home Assistant.

I'm on the latest 2023.6.2 version, running Home Assistant OS on a Raspberry Pi 4.

**Unexpected error fetching biketrax-XXX@gmail.com-subscription data: Parser must be a string or character stream, not NoneType**

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/biketrax/coordinator.py", line 144, in _async_update_data
    await device.update_subscription()
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/client.py", line 211, in update_subscription
    ] = await self._account.admin_api.get_subscription(self._device.unique_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 49, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/api.py", line 578, in get_subscription
    return models.subscription_from_dict(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 857, in subscription_from_dict
    return Subscription.from_dict(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 250, in from_dict
    trial_end = from_datetime(obj.get("trialEnd"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiobiketrax/models.py", line 54, in from_datetime
    return dateutil.parser.parse(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
                ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dateutil/parser/_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
```

**Comment by basilfx** [comment]
It seems to be related to the `trialEnd` being `null`, where a string (timestamp) was expected.

Can you try to enable API response logging, by adding this to your HASS configuration?

```
logger:
  default: warning
  logs:
    aiobiketrax: debug
    aiobiketrax.responses: debug
```

Then post the call that goes to `https://admin.powunity.com/api/subscriptions/<unique id>`. Be sure to anonymize sensitive data.

(It also might be sufficient if you have logged into `https://app.powunity.com` and then visit the link above, replacing the unique identifier of course, which you can find that in the settings page.)

**Comment by basilfx** [comment]
Yes, that is what I also suspected. The category is B2B, whereas it 'normally' reads B2C. I know what to fix. Can do this tomorrow or the day after, hopefully.

**Comment by gyusza** [comment]
Amazing, thank you very much!

**Comment by gyusza** [comment]
Hey @basilfx just wanted to check-in that as soon as I realised that your update is to the aiobiketrax repo and not this, followed the instructions on getting it updated to the latest version in HASSIO, the tracking now works. I do face the issue that now the application (PowUnity iOS app) has been disconnected, but I can live with that. Is that expected?

**Comment by basilfx** [comment]
Hi @gyusza, that should not be the case, and I don't see why that should happen. Did it work when you signed in again?

I do recon that from time to time I need to sign in again (especially in the browser), but that seems to be related to expired sessions.

**Comment by basilfx** [comment]
Also, I will prepare another release, but I was also waiting for some findings of #92, but that seems to be unrelated at this moment.

**Comment by basilfx** [comment]
@gyusza I did notice that if I toggle the 'stolen' option from within Home Assistant, the BikeTrax app shows my license expired. However, everything kept on working, and if I manually performed the request to 'update' the trial date attribute of a device, I could change it into whatever I want.

**Comment by basilfx** [comment]
Version 1.1.0 has been released. Please open a new issue if you encounter problems with it.
